server:
  port: 8301
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8900
security:
  oauth2:
    resource:
      jwt:
        key-value: paper #注意这里要跟验证服务器的密钥一致，这样算出来的签名才会一致

