spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/apaperlight/paperlight.git
          search-paths:
            - SpringCloudStudy
          label: main
server:
  port: 8700
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
