server:
  port: 8201
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ephemeral: true
#        cluster-name: Chongqing
    loadbalancer:
      nacos:
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8900
security:
  oauth2:
    resource:
      jwt:
        key-value: paper #注意这里要跟验证服务器的密钥一致，这样算出来的签名才会一致
feign:
  oauth2:
    enabled: true
    load-balanced: true