server:
  port: 8201
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ephemeral: true
#        cluster-name: Chongqing
    loadbalancer:
      nacos:
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8900